import math
import os

def generate_trig_tables():
    # 32方向の角度（1周 = 32分割）
    ANGLES = 32
    SCALE = 256  # 256倍（下位8bit精度）
    
    cos_values = []
    sin_values = []
    
    for i in range(ANGLES):
        # 32分割された角度をラジアンに変換
        # 0 -> 0度, 8 -> 90度, 16 -> 180度, 24 -> 270度
        angle_deg = i * (360.0 / ANGLES)
        rad = math.radians(angle_deg)
        
        # 256倍して四捨五入（round）
        cos_scaled = round(math.cos(rad) * SCALE)
        sin_scaled = round(math.sin(rad) * SCALE)
        
        # 45度などの特殊な境界で256を超えないよう、念のため-256〜256にクリップ
        cos_scaled = max(-SCALE, min(SCALE, cos_scaled))
        sin_scaled = max(-SCALE, min(SCALE, sin_scaled))
        
        cos_values.append(cos_scaled)
        sin_values.append(sin_scaled)
        
    # C言語のヘッダファイル形式の文字列を生成
    output = []
    output.append("/* Automatically generated by gen-sincos.py */")
    output.append("#ifndef SINCOS_H")
    output.append("#define SINCOS_H")
    output.append("")
    output.append("#include <stdint.h>")
    output.append("")
    output.append(f"#define TABLE_ANGLES {ANGLES}")
    output.append("")
    
    # cosテーブルの出力
    output.append("/* Fixed-point cos table (1.0 = 256) */")
    output.append(f"const int16_t cos_table[{ANGLES}] = {{")
    output.append("    " + ", ".join(f"{v:4d}" for v in cos_values))
    output.append("};")
    output.append("")
    
    # sinテーブルの出力
    output.append("/* Fixed-point sin table (1.0 = 256) */")
    output.append(f"const int16_t sin_table[{ANGLES}] = {{")
    output.append("    " + ", ".join(f"{v:4d}" for v in sin_values))
    output.append("};")
    output.append("")
    output.append("#endif /* SINCOS_H */")
    
    return "\n".join(output)

if __name__ == "__main__":
    # 出力先を src/sincos.h に設定
    # ディレクトリがない場合は作成
    os.makedirs("../src", exist_ok=True)
    
    header_content = generate_trig_tables()
    
    with open("../src/sincos.h", "w", encoding="utf-8") as f:
        f.write(header_content)
        
    print("Successfully generated: ../src/sincos.h")