/* Automatically generated by gen-sincos.py */
#ifndef SINCOS_H
#define SINCOS_H

#include <stdint.h>

#define TABLE_ANGLES 32

/* Fixed-point cos table (1.0 = 256) */
const int16_t cos_table[TABLE_ANGLES] = {
  256,  251,  237,  213,  181,  142,   98,   50,
    0,  -50,  -98, -142, -181, -213, -237, -251,
 -256, -251, -237, -213, -181, -142,  -98,  -50,    
    0,   50,   98,  142,  181,  213,  237,  251
};

/* Fixed-point sin table (1.0 = 256) */
const int16_t sin_table[TABLE_ANGLES] = {
    0,   50,   98,  142,  181,  213,  237,  251,  
  256,  251,  237,  213,  181,  142,   98,   50,    
    0,  -50,  -98, -142, -181, -213, -237, -251, 
 -256, -251, -237, -213, -181, -142,  -98,  -50
};

#endif /* SINCOS_H */